/**
 * /api/airdrop/proof/[wallet].js
 * Vercel serverless function — serves merkle proof for a wallet
 * Reads from proofs.json (generated by scripts/generateMerkleTree.js)
 *
 * Deploy proofs.json alongside this function or store in Vercel KV / Supabase
 */
import proofsData from '../../../scripts/output/proofs.json' assert { type: 'json' }

export default function handler(req, res) {
  const { wallet } = req.query
  if (!wallet) return res.status(400).json({ error: 'wallet required' })

  const addr = wallet.toLowerCase()
  const entry = proofsData[addr]

  if (!entry) {
    return res.status(404).json({ error: 'Wallet not eligible', wallet: addr })
  }

  return res.status(200).json({
    wallet: addr,
    amountAeth: entry.amountAeth,
    amountWei: entry.amountWei,
    isPioneer: entry.isPioneer,
    proof: entry.proof,
  })
}
